language: csharp
solution: DigitalWorkSpace.sln
mono: none
dotnet: 3.1
before_install:
  - cd Src
install:
  - dotnet restore DigitalWorkSpace/DigitalWorkSpace.sln
script:
  - dotnet build DigitalWorkSpace/DigitalWorkSpace.sln
  - dotnet test DigitalWorkSpace/DigitalWorkSpace.sln