language: csharp
mono: latest
dotnet: 3.1
solution: DigitalWorkSpace.sln
before_install:
  - cd Src
install:
  - nuget restore DigitalWorkSpace/DigitalWorkSpace.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - dotnet restore
  - dotnet test