apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: catalogscontainer
  spec:
    ports:
    - name: "8084"
      port: 8084
      targetPort: 80
    - name: "44386"
      port: 44386
      targetPort: 443
    selector:
      app: catalogscontainer
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    name: catalogdbcontainer
  spec:
    ports:
    - name: "3308"
      port: 3308
      targetPort: 3306
    selector:
      app: catalogdbcontainer
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: catalogscontainer
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: catalogscontainer
    template:
      metadata:
        labels:
          app: catalogscontainer
      spec:
        containers:
        - image: practicecr.azurecr.io/dws/tinyurls
          name: catalogscontainer
          ports:
          - containerPort: 80
          - containerPort: 443
          resources: {}
        restartPolicy: Always
  status: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: catalogdbcontainer
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: catalogdbcontainer
    template:
      metadata:
        labels:
          app: catalogdbcontainer
      spec:
        containers:
        - env:
          - name: MYSQL_ROOT_PASSWORD
            value: root
          image: practicecr.azurecr.io/dws/urldb
          name: catalogdbcontainer
          ports:
          - containerPort: 3306
          resources: {}
        restartPolicy: Always
  status: {}
kind: List
metadata: {}

