apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: mykafka
  spec:
    ports:
    - name: "9092"
      port: 9092
      targetPort: 9092
    - name: "29092"
      port: 29092
      targetPort: 29092
    - name: "29094"
      port: 29094
      targetPort: 29094
    selector:
      app: mykafka
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    name: myzookeeper
  spec:
    ports:
    - name: "2181"
      port: 2181
      targetPort: 2181
    selector:
      app: myzookeeper
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: mykafka
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: mykafka 
    template:
      metadata:
        labels:
          app: mykafka
      spec:
        containers:
        - env:
          - name: KAFKA_ADVERTISED_LISTENERS
            value: LISTENER_INTERNAL://mykafka:9092,LISTENER_HOST://localhost:29092,LISTENER_EXTERNAL://ALWAYSKFKA:29094
          - name: KAFKA_AUTO_CREATE_TOPIC_ENABLE
            value: "true"
          - name: KAFKA_DEFAULT_REPLICATION_FACTOR
            value: "1"
          - name: KAFKA_INTER_BROKER_LISTENER_NAME
            value: LISTENER_INTERNAL
          - name: KAFKA_LISTENERS
            value: LISTENER_INTERNAL://mykafka:9092,LISTENER_HOST://mykafka:29092,LISTENER_EXTERNAL://MYKAFKA:29094
          - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            value: LISTENER_INTERNAL:PLAINTEXT,LISTENER_HOST:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT
          - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            value: "1"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: zookeeper:2181
          image: confluentinc/cp-kafka:5.5.1
          name: mykafka
          ports:
          - containerPort: 9092
          - containerPort: 29092
          - containerPort: 29094
          resources: {}
        restartPolicy: Always
  status: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: myzookeeper
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: myzookeeper    
    template:
      metadata:
        labels:
          app: myzookeeper
      spec:
        containers:
        - env:
          - name: ZOOKEEPER_CLIENT_PORT
            value: "2181"
          image: confluentinc/cp-zookeeper:5.5.1
          name: myzookeeper
          ports:
          - containerPort: 2181
          resources: {}
        restartPolicy: Always
  status: {}
kind: List
metadata: {}

