apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: dwsuicontainer
  spec:
    ports:
    - name: "4200"
      port: 4200
      targetPort: 80
    selector:
      app: dwsuicontainer
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: dwsuicontainer
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: dwsuicontainer
    template:
      metadata:
        labels:
          app: dwsuicontainer
      spec:
        containers:
        - env:
          - name: MYSQL_ROOT_PASSWORD
            value: root
          image: practicecr.azurecr.io/dws/dwsui
          name: dwsuicontainer
          ports:
          - containerPort: 80
          resources: {}
        restartPolicy: Always
  status: {}
kind: List
metadata: {}

