apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: userscontainer
  spec:
    ports:
    - name: "8082"
      port: 8082
      targetPort: 80
    - name: "44384"
      port: 44384
      targetPort: 443
    selector:
      app: userscontainer
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    name: userdbcontainer
  spec:
    ports:
    - name: "3310"
      port: 3310
      targetPort: 3306
    selector:
      app: userdbcontainer
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: userscontainer
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: userscontainer
    template:
      metadata:
        labels:
          app: userscontainer
      spec:
        containers:
        - image: practicecr.azurecr.io/dws/users
          name: userscontainer
          ports:
          - containerPort: 80
          - containerPort: 443
          resources: {}
        restartPolicy: Always
  status: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: userdbcontainer
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: userdbcontainer
    template:
      metadata:
        labels:
          app: userdbcontainer
      spec:
        containers:
        - env:
          - name: MYSQL_ROOT_PASSWORD
            value: root
          image: practicecr.azurecr.io/dws/userdb
          name: userdbcontainer
          ports:
          - containerPort: 3306
          resources: {}
        restartPolicy: Always
  status: {}
kind: List
metadata: {}

